### PR TITLE
fix issue with elevation and notification

### LINKED ISSUE #1396: Layer Notification example broken
At https://design-system.hpe.design/components/layer#notifications, clicking "Show me the notification" results in:

Screen Shot 2021-01-29 at 2 04 15 PM

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
This PR fixes the issue with the layer notification
#### Where should the reviewer start?
LayerNotificationExample.js
#### What testing has been done on this PR?
on site
#### What are the relevant issues?
Closes #1396 
#### Is this change backwards compatible or is it a breaking change?
yes

### CODE REVIEW

File: aries-site/src/examples/components/layer/LayerNotificationExample.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import React, { useState } from 'react';
+import React, { useState }  from 'react';
```
Comment (taysea) [inline aries-site/src/examples/components/layer/LayerNotificationExample.js:1]:
```suggestion
import React, { useState } from 'react';
```

**Comment by taysea** [comment]
Things look fine w your changes, but the snapshot changes are coming from an issue with the theme re: button sizing. The dimensions are no longer lining up with Figma. I'd like to wait to merge this PR until we resolve the theme issue with Button so snapshots are not affected.
