### PR TITLE
Fix % complete

### LINKED ISSUE #1584: Accessibility Issue: “% Complete” column is graphical, and not readable for a screen reader.
“% Complete” column is graphical, and not readable for a screen reader. 
This % Complete column is using color alone to convey information. If the color had a visual representation as well as color it would pass. Also, think about adding a numeric indication that could also be picked up by the screen reader.

Screen Shot 2021-04-26 at 11 49 23 AM

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
Add percentages next to meter for screen readers 
#### Where should the reviewer start?
table.js 
#### Any background context you want to provide?
The  column was graphical, and not readable for a screen reader
#### What are the relevant issues?
closes #1584

### CODE REVIEW

File: aries-site/src/examples/components/pagination/PaginationTableExample.js [hunk 1]
```diff
@@ -487,13 +487,15 @@ const columns = [
       </Box>
     ),
     render: datum => (
-      <Box pad={{ vertical: 'xsmall' }}>
+      <Box direction="row" gap="xxsmall" pad={{ vertical: 'xsmall' }}>
```
Comment (taysea) [inline aries-site/src/examples/components/pagination/PaginationTableExample.js:490]: For some reason it looks like the rows are taller now than before but I'm not sure why on first glance. Don't think the row height should increase:

BEFORE:
Screen Shot 2021-05-06 at 4 12 37 PM

AFTER:
Screen Shot 2021-05-06 at 4 12 28 PM

File: aries-site/src/examples/components/pagination/PaginationTableExample.js [hunk 2]
```diff
@@ -487,13 +487,15 @@ const columns = [
...
         <Meter
+          alignSelf="center"
           values={[{ value: datum.pinned / datum.pinnable, color: 'graph-2' }]}
           max={1}
           thickness="small"
           size="small"
         />
+        <Text>{((datum.pinned / datum.pinnable) * 10).toFixed(0)}%</Text>
```
Comment (taysea) [inline aries-site/src/examples/components/pagination/PaginationTableExample.js:498]:
```suggestion
        <Text>{((datum.pinned / datum.pinnable) * 100).toFixed(0)}%</Text>
```
Think it should be * 100, this looks like "80%"
Screen Shot 2021-05-06 at 4 13 32 PM

Comment (taysea) [reply aries-site/src/examples/components/pagination/PaginationTableExample.js:498]: If so we should adjust in the other examples also

File: aries-site/src/examples/components/pagination/PaginationTableExample.js (hunk 1 above)
Comment (britt6612) [reply aries-site/src/examples/components/pagination/PaginationTableExample.js:490]: oh good catch I didnt even see that let me go back and inspect

Comment (britt6612) [reply aries-site/src/examples/components/pagination/PaginationTableExample.js]: so it was the `box` around `meter`  had a vertical `pad` so that was also going to the `text` so I closed that `box` before `text`

**Review by taysea — APPROVED** [review]
LGTM.
