### PR TITLE
Fix search focus

### LINKED ISSUE #1532: Clicking within an active search closes search
When you click on the search icon then click in the search input it closes the search. 
image

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
This PR adds a `onBlur` this `onBlur` sets `focus` to false as long as the user is not interacting with the drop.
#### Where should the reviewer start?
aries-site/src/layouts/navigation/Search.js
#### What testing has been done on this PR?
Ran the testcafe 
#### How should this be manually tested?
click on the search and you will see that as long as you click within the `textinput` it will stay focused.
Also tabbing on keyboard and and clicking a suggestion. 
#### Any background context you want to provide?
https://github.com/grommet/hpe-design-system/issues/1532
#### What are the relevant issues?
closes #1532 
#### Should this PR be mentioned in Design System updates?
no
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

File: aries-site/src/layouts/navigation/Search.js [hunk 1]
```diff
@@ -88,12 +88,18 @@ export const Search = ({ focused, setFocused }) => {
...
-              onSelect={onSelect}
+              onSuggestionSelect={onSelect}
               suggestions={suggestions}
-              onSuggestionsClose={() => setFocused(false)}
               value={value}
               plain
               reverse
+              onBlur={event => {
+                // Only treat it as a blur if the element receiving focus
+                // isn't in our drop. The relatedTarget will be our drop
```
Comment (taysea) [inline aries-site/src/layouts/navigation/Search.js:98]: Good comment, thanks!

File: aries-site/src/layouts/navigation/Search.js [hunk 2]
```diff
@@ -65,9 +65,9 @@ export const Search = ({ focused, setFocused }) => {
 
   const onSelect = event => {
     const href = nameToPath(event.suggestion);
-
     if (internalLink.test(href)) {
       router.push(href);
+      setFocused(false);
```
Comment (taysea) [inline aries-site/src/layouts/navigation/Search.js:70]: Do we need to add this here? If the site navigates will setFocused already change to false?

Comment (britt6612) [reply aries-site/src/layouts/navigation/Search.js:70]: yes I added it because with keyboard usage without setting `focus(false)` the input was staying open after the user selected a  suggestion and clicked enter.

Comment (taysea) [reply aries-site/src/layouts/navigation/Search.js:70]: Great, thanks for clarifying.

**Review by taysea — APPROVED** [review]
LGTM. Nice job.

**Review by halocline — APPROVED** [review]
