### PR TITLE
fix layer modal to match figma

### LINKED ISSUE #2332: Update 'Center modal' example on site
Match the 'center modal example' as per Figma. We have added subtle to the example and this has to match in site accordingly.

### PR DESCRIPTION
**Pull request by britt6612**
[Deploy Preview](https://deploy-preview-2391--keen-mayer-a86c8b.netlify.app/components/layer?q=layer#center-modal)

#### What does this PR do?
This PR aligns the `layer` modal with Figma
#### Where should the reviewer start?
LayerCenterExample.js
#### What testing has been done on this PR?
site
In addition to the feature you are implementing, have you checked the following:

**General UX Checks**
- [x] Small, medium, and large screen sizes
- [x] Cross-browsers (FireFox, Chrome, and Safari)
- [x] Light & dark modes
- [x] All hyperlinks route properly

**Accessibility Checks**
- [x] Keyboard interactions
- [x] Screen reader experience
- [x] Run WAVE accessibility plugin (Chrome)

**Code Quality Checks**
- [x] Console is free of warnings and errors
- [ ] Passes E2E commit checks
- [ ] Visual snapshots are reasonable

#### How should this be manually tested?
site
#### Any background context you want to provide?
A subtitle was added as an option to the layer modal as well as the correct heading size 
#### What are the relevant issues?
closes #2332 
#### Should this PR be mentioned in Design System updates?
yes
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

File: aries-site/src/examples/components/layer/LayerCenterExample.js [hunk 1]
```diff
@@ -25,18 +33,21 @@ export const LayerCenterExample = () => {
                 <Box justify="center">
                   <MailOption />
                 </Box>
-                <Heading margin="none" level={2}>
+                <Heading margin="none" level={4}>
```
Comment (taysea) [inline aries-site/src/examples/components/layer/LayerCenterExample.js:36]: Based on our [Layer guidance](https://design-system.hpe.design/components/layer?q=layer#using-headings-in-layer), I think this should remain as h2 (and adjust the size accordingly). We should update Figma in this case.

File: aries-site/src/examples/components/layer/LayerCenterExample.js [hunk 2]
```diff
@@ -25,18 +33,21 @@ export const LayerCenterExample = () => {
...
               <Box justify="center">
                 <Button icon={<FormClose />} onClick={onClose} />
               </Box>
             </Box>
+            <Paragraph margin="none">A subtitle if needed</Paragraph>
             <Box overflow="auto" pad={{ vertical: 'medium' }}>
               <Text>
-                For modal dialogs, the use case will determine the design and
-                size of the box for your content
+                The width of this modal dialog is 384px with 12px corner radius.
```
Comment (taysea) [inline aries-site/src/examples/components/layer/LayerCenterExample.js:47]: I am inclined to reference the width and corner radius in tshirt sizes, with px as supporting if we need it. Trying to reinforce language of tshirt sizes
```suggestion
                The width of this modal dialog is 'medium' (384px) with 'small' (12px) corner radius.
```

File: aries-site/src/examples/components/layer/LayerCenterExample.js (hunk 1 above)
Comment (britt6612) [reply aries-site/src/examples/components/layer/LayerCenterExample.js:36]: okay yes Ill let Keeth know if we go that route and change it back!

File: aries-site/src/examples/components/layer/LayerCenterExample.js [hunk 3]
```diff
@@ -25,18 +33,21 @@ export const LayerCenterExample = () => {
...
+                The box component has 24px padding. For modal dialogs, the use
```
Comment (taysea) [inline aries-site/src/examples/components/layer/LayerCenterExample.js:48]:
```suggestion
                The Box component has 'medium' 24px padding. For modal dialogs, the use
```

File: aries-site/src/examples/components/layer/LayerCenterExample.js (hunk 1 above)
Comment (britt6612) [reply aries-site/src/examples/components/layer/LayerCenterExample.js]: I changed this back let me know if this is okay

**Review by halocline — COMMENTED** [review]
@britt6612 @taysea Can we huddle and talk through the accessibility aspects of this modal?

Also, after yesterday's discussion, I am thinking about the content of this example vs. a modal size defined by its content. Perhaps we might have additional examples for:
- Example where the content highlights the accessibility aspects such as where focus should be placed? Proper roles, etc.?
- Example where the content drives the size of the modal

File: aries-site/src/examples/components/layer/LayerCenterExample.js [hunk 4]
```diff
@@ -25,18 +33,21 @@ export const LayerCenterExample = () => {
                 <Box justify="center">
                   <MailOption />
```
Comment (halocline) [inline aries-site/src/examples/components/layer/LayerCenterExample.js:34]: Can we confirm the icon being used here? The one in Figma seems rounded which is the aesthetic to which we are headed. It would be good for us to be aligned.

May require follow on issues.

File: aries-site/src/examples/components/layer/LayerCenterExample.js [hunk 5]
```diff
@@ -25,18 +33,21 @@ export const LayerCenterExample = () => {
...
                   Modal Dialog
                 </Heading>
               </Box>
               <Box justify="center">
                 <Button icon={<FormClose />} onClick={onClose} />
               </Box>
             </Box>
+            <Paragraph margin="none">A subtitle if needed</Paragraph>
             <Box overflow="auto" pad={{ vertical: 'medium' }}>
               <Text>
```
Comment (halocline) [inline aries-site/src/examples/components/layer/LayerCenterExample.js:46]: Shouldn't this be a Paragraph?

File: aries-site/src/examples/components/layer/LayerCenterExample.js [hunk 6]
```diff
@@ -25,18 +33,21 @@ export const LayerCenterExample = () => {
...
-                <Heading margin="none" level={2}>
+                <Heading margin="none" size="small" level={2}>
                   Modal Dialog
                 </Heading>
               </Box>
               <Box justify="center">
                 <Button icon={<FormClose />} onClick={onClose} />
               </Box>
             </Box>
+            <Paragraph margin="none">A subtitle if needed</Paragraph>
```
Comment (halocline) [inline aries-site/src/examples/components/layer/LayerCenterExample.js:44]: This seems like it should be Text not Paragraph and the copy below, Paragraph, not Text.

File: aries-site/src/examples/components/layer/LayerCenterExample.js (hunk 4 above)
Comment (britt6612) [reply aries-site/src/examples/components/layer/LayerCenterExample.js:34]: I may have to follow up because I looked through our icons and I do not see this one

Comment (britt6612) [reply aries-site/src/examples/components/layer/LayerCenterExample.js:34]: Screen Shot 2022-02-25 at 3 09 30 PM
I dont see a rounded email in our icons 😕

Comment (britt6612) [reply aries-site/src/examples/components/layer/LayerCenterExample.js:34]: made a new ticket to look into icon
https://github.com/grommet/hpe-design-system/issues/2400

**Review by halocline — APPROVED** [review]
