### PR TITLE
fix pageheader fix anatomy

### LINKED ISSUE #2813: Design System Site - PageHeader buttons not responding correctly
The buttons on the PageHeader component look like they're not responding correctly. :D Please correct responsiveness. Thank you
Screen Shot 2022-08-11 at 11 37 52 AM

### PR DESCRIPTION
**Pull request by britt6612**
[Deploy Preview](https://deploy-preview-3001--keen-mayer-a86c8b.netlify.app/components/pageheader)

#### What does this PR do?
fixes the diagram for the `buttons` in the PageHeader anatomy  
#### Where should the reviewer start?
PageHeaderAnatomy.js
#### What testing has been done on this PR?
site 
In addition to the feature you are implementing, have you checked the following:

**General UX Checks**
- [ ] Small, medium, and large screen sizes
- [ ] Cross-browsers (FireFox, Chrome, and Safari)
- [ ] Light & dark modes
- [ ] All hyperlinks route properly

**Accessibility Checks**
- [ ] Keyboard interactions
- [ ] Screen reader experience
- [ ] Run WAVE accessibility plugin (Chrome)

**Code Quality Checks**
- [ ] Console is free of warnings and errors
- [ ] Passes E2E commit checks
- [ ] Visual snapshots are reasonable

#### What are the relevant issues?
closes #2813 
#### Should this PR be mentioned in Design System updates?
no
#### Is this change backwards compatible or is it a breaking change?
 backwards compatible

### CODE REVIEW

**Review by MikeKingdom — COMMENTED** [review]
It has some alignment problems when it gets small:
image

This is what it did before the change:
image

File: aries-site/src/examples/components/pageheader/PageHeaderAnatomy.js [hunk 1]
```diff
@@ -53,7 +53,7 @@ export const PageHeaderAnatomy = ({ background }) => {
     <Stack>
       <Grid
         align="center"
-        columns={['auto', 'flex', 'auto']}
+        columns={['30px', 'flex', '30px']}
```
Comment (halocline) [inline aries-site/src/examples/components/pageheader/PageHeaderAnatomy.js:56]: why fixed pixel values?

File: aries-site/src/examples/components/pageheader/utils.js [hunk 2]
```diff
@@ -2,7 +2,7 @@ export const groupActions = (actions, breakpoint, bestPractice) => {
   let collapsedActions;
   let displayedActions;
   // collapse all default/secondary actions
-  if (breakpoint === 'medium') {
+  if (['medium', 'large'].includes(breakpoint)) {
```
Comment (halocline) [inline aries-site/src/examples/components/pageheader/utils.js:5]: My expectation is that action items will only collapse into the overflow menu [when space runs out](https://design-system.hpe.design/components/pageheader#responsive-behavior-and-content-prioritization). This is collapsing when plenty of space is still available:

Screen Shot 2022-10-25 at 1 41 18 PM

I would expect that the actions area probably has unique definitions across breakpoints.

File: aries-site/src/examples/components/pageheader/PageHeaderAnatomy.js (hunk 1 above)
Comment (britt6612) [reply aries-site/src/examples/components/pageheader/PageHeaderAnatomy.js:56]: matches the values for what was given for `rows` 
going to try another approach though

File: aries-site/src/examples/components/pageheader/utils.js (hunk 2 above)
Comment (britt6612) [reply aries-site/src/examples/components/pageheader/utils.js:5]: right here if all 3 buttons were shown they would wrap because the fact we have the anatomy grid laid over the PageHeader grid the breakpoints arent working smoothly so Im going to try and build it all into one grid.

File: aries-site/src/examples/components/pageheader/utils.js [hunk 3]
```diff
@@ -5,6 +5,12 @@ export const groupActions = (actions, breakpoint, bestPractice) => {
   if (breakpoint === 'medium') {
     collapsedActions = actions.filter(action => !action.primary);
     displayedActions = actions.filter(action => action.primary);
+    // only leave primary and secondary visable
+  } else if (breakpoint === 'large') {
```
Comment (britt6612) [inline aries-site/src/examples/components/pageheader/utils.js:9]: The thought process for collapsedActions and DisplayedActions:

- Show all 3 buttons at xlarge
- Show overflow menu + 2 buttons at large
- Show overflow menu + primary button at medium

File: aries-site/src/themes/aries.js [hunk 4]
```diff
@@ -6,6 +6,14 @@ export const aries = deepMerge(hpe, {
   // To be stripped out once theme changes are made in grommet-theme-hpe.
   // keeping file for use as playground for future theme adjusments that need
   // to be quickly tested
+  pageHeader: {
+    large: {
+      columns: [['small', 'flex'], 'auto'],
+    },
+    xlarge: {
+      columns: [['medium', 'flex'], 'auto'],
```
Comment (britt6612) [inline aries-site/src/themes/aries.js:14]: Needed to change the values for the anatomy we can have a separate `grid` for anatomy put this in here to view and see if we want to go that approach. The problem Im running into is even though the screen size is `large`  or `medium` the anatomy is not taking up the whole area due to the side nav and the way the page is laid out so I needed to shrink these values for the Title so the buttons are left with enough room not to wrap.

Comment (britt6612) [reply aries-site/src/themes/aries.js:14]: @taysea

Comment (taysea) [reply aries-site/src/themes/aries.js:14]: I'm not following why we have this in `aries.js` -- is your thought that we will only adjust the pageHeader Grid definition for the anatomy diagram? I'm not following why we need something separate than what the other page header examples need.

File: aries-site/src/examples/components/pageheader/utils.js (hunk 3 above)
Comment (taysea) [reply aries-site/src/examples/components/pageheader/utils.js:9]: This makes sense

File: aries-site/src/themes/aries.js (hunk 4 above)
Comment (britt6612) [reply aries-site/src/themes/aries.js:14]: I had this here to demo the changes for the anatomy to make sure were on the same page then I can pull this out and make a new grid for the anatomy diagram. If we like these values

Comment (britt6612) [reply aries-site/src/themes/aries.js]: took it out of `aries.js` and put theme.extend like we discussed

File: aries-site/src/examples/components/pageheader/PageHeaderAnatomy.js [hunk 5]
```diff
@@ -1,9 +1,24 @@
 import React, { useContext } from 'react';
 import PropTypes from 'prop-types';
-import { Diagram, Grid, ResponsiveContext, Stack } from 'grommet';
+import { Diagram, Grid, ResponsiveContext, Stack, ThemeContext } from 'grommet';
 import { Annotation } from '../../../layouts';
 import { PageHeaderContentRegions } from '.';
 
+// need to overrid the PageHeader theme values in order for our anatomy
```
Comment (taysea) [inline aries-site/src/examples/components/pageheader/PageHeaderAnatomy.js:7]:
```suggestion
// need to override the PageHeader theme values in order for our anatomy
```

File: aries-site/src/examples/components/pageheader/PageHeaderAnatomy.js [hunk 6]
```diff
@@ -1,9 +1,24 @@
...
+// to fit correctly on the page. Even though it is using the correct breakpoints
+// our anatomy are only taking up half the space on the page so layout different than
+// a PageHeader on a full page.
+const PageHeaderSiteTheme = {
```
Comment (taysea) [inline aries-site/src/examples/components/pageheader/PageHeaderAnatomy.js:11]:
```suggestion
const pageHeaderSiteTheme = {
```
small suggestion to align with conventions for capitalization

File: aries-site/src/examples/components/pageheader/PageHeaderAnatomy.js [hunk 7]
```diff
@@ -73,17 +88,19 @@ export const PageHeaderAnatomy = ({ background }) => {
...
               ]
         }
-        gap={{ column: 'large' }}
+        gap={{ column: 'small' }}
       >
         <Annotation id={2} target="2" gridArea="annotation-2" />
         <Annotation id="1a" target="1a" gridArea="annotation-1a" />
         <Annotation id="1b" target="1b" gridArea="annotation-1b" />
         <Annotation id={3} target="3" gridArea="annotation-3" />
+        <ThemeContext.Extend value={PageHeaderSiteTheme}>
```
Comment (taysea) [inline aries-site/src/examples/components/pageheader/PageHeaderAnatomy.js:97]:
```suggestion
        <ThemeContext.Extend value={pageHeaderSiteTheme}>
```

File: aries-site/src/examples/components/pageheader/PageHeaderResponsiveActions.js [hunk 8]
```diff
@@ -7,10 +7,29 @@ import {
...
+  ThemeContext,
 } from 'grommet';
 import { groupActions } from './utils';
 import { ActionMenu, ReverseAnchor } from '../../templates';
 
+// need to overrid the PageHeader theme values in order for our examples 
+// to fit their container page. Even though it is using the correct breakpoints
+// our examples are only taking up half the space on the page so layout different than
+// a PageHeader on a full page.
+const PageHeaderSiteTheme = {
```
Comment (taysea) [inline aries-site/src/examples/components/pageheader/PageHeaderResponsiveActions.js:19]: instead of repeating this in 2 places, can we define it in a single file and import to the 2 examples?

File: aries-site/src/examples/components/pageheader/utils.js [hunk 9]
```diff
@@ -5,6 +5,12 @@ export const groupActions = (actions, breakpoint, bestPractice) => {
   if (breakpoint === 'medium') {
     collapsedActions = actions.filter(action => !action.primary);
     displayedActions = actions.filter(action => action.primary);
+    // only leave primary and secondary visable
```
Comment (taysea) [inline aries-site/src/examples/components/pageheader/utils.js:8]:
```suggestion
    // only leave primary and secondary visible
```

**Review by taysea — COMMENTED** [review]
Just a few cleanups but the approach I am good with.

File: aries-site/src/examples/components/pageheader/PageHeaderResponsiveActions.js (hunk 8 above)
Comment (britt6612) [reply aries-site/src/examples/components/pageheader/PageHeaderResponsiveActions.js:19]: one is a little different than the other as it contains `medium` for the dos and don't example since those have a smaller width I had to change them

Comment (taysea) [reply aries-site/src/examples/components/pageheader/PageHeaderResponsiveActions.js:19]: oh gotcha, okay that's fine. can we adjust the capitalization to `pageHeaderSiteTheme` here too?

Comment (britt6612) [reply aries-site/src/examples/components/pageheader/PageHeaderResponsiveActions.js]: done

**Review by taysea — APPROVED** [review]

**Review by halocline — APPROVED** [review]
